// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMC4tYUZNWavV1tBDojqctaens7s3-9Uw',
    appId: '1:603285234851:web:8ffe61e083bec5fedf8b16',
    messagingSenderId: '603285234851',
    projectId: 'chatappp-ee689',
    authDomain: 'chatappp-ee689.firebaseapp.com',
    storageBucket: 'chatappp-ee689.appspot.com',
    measurementId: 'G-S5Q2Q6B0TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1L482gGxJ0ucjFb18A3-Pp1FYQWX2vCQ',
    appId: '1:603285234851:android:a8647a810f3e5aa9df8b16',
    messagingSenderId: '603285234851',
    projectId: 'chatappp-ee689',
    storageBucket: 'chatappp-ee689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLm_rsRRdKi8gor1WsOUMeJRyWp1iFSGk',
    appId: '1:603285234851:ios:b583877041cf61e2df8b16',
    messagingSenderId: '603285234851',
    projectId: 'chatappp-ee689',
    storageBucket: 'chatappp-ee689.appspot.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLm_rsRRdKi8gor1WsOUMeJRyWp1iFSGk',
    appId: '1:603285234851:ios:b583877041cf61e2df8b16',
    messagingSenderId: '603285234851',
    projectId: 'chatappp-ee689',
    storageBucket: 'chatappp-ee689.appspot.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMC4tYUZNWavV1tBDojqctaens7s3-9Uw',
    appId: '1:603285234851:web:14b45372bed25a10df8b16',
    messagingSenderId: '603285234851',
    projectId: 'chatappp-ee689',
    authDomain: 'chatappp-ee689.firebaseapp.com',
    storageBucket: 'chatappp-ee689.appspot.com',
    measurementId: 'G-XRBNDCKM8P',
  );
}
